[package]
name = "fido-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounded-vec = { version = "0.7.1", features = ["serde"] }
serde = { version = "1", features = ["derive"], optional = true }

[features]
serde = ["dep:serde", "bounded-vec/serde"]
